// ============ PROGRESS ATMOSPHERE ============
// Today is open nature. Nourish is a kitchen garden. Bloom is a conservatory.
// Cycle is a bound journal. Progress is a quiet evening sky behind an
// editorial page — a handful of oversized, soft-edged watercolor stars living
// along the outer borders, mostly cropped off-screen. Not sparkle, not a
// pattern — atmosphere, framing clean content in the center.
//
// Everything here is decorative and inert (pointerEvents: none) and sits
// BEHIND the page content, never over the chart or numbers that matter.
//
// IMPORTANT — no Math.random() anywhere in this file. Star shapes must be
// identical on server and client render or React throws a hydration
// mismatch. Every "irregular, painterly" shape below is generated by a small
// deterministic seeded generator instead, so the same seed always produces
// the exact same shape.

// ── deterministic PRNG (Park–Miller) — same seed, same output, always ──────
function seededRand(seed) {
  let s = seed % 2147483647
  if (s <= 0) s += 2147483646
  return () => { s = (s * 16807) % 2147483647; return (s - 1) / 2147483646 }
}

// ── an irregular, hand-painted-feeling star silhouette ──────────────────────
// Alternates outer/inner points around a circle with small deterministic
// jitter on both angle and radius, then threads a smooth closed Catmull-Rom
// curve through them (converted to cubic Beziers) so the outline is soft and
// slightly uneven rather than a crisp geometric star.
function starPoints(seed, spikes) {
  const rand = seededRand(seed)
  const n = (spikes || 5) * 2
  const pts = []
  for (let i = 0; i < n; i++) {
    const isOuter = i % 2 === 0
    const baseR = isOuter ? 92 : 40
    const r = baseR + (rand() - 0.5) * 16
    const angle = (i / n) * Math.PI * 2 + (rand() - 0.5) * 0.22
    pts.push([100 + Math.cos(angle) * r, 100 + Math.sin(angle) * r])
  }
  return pts
}

function catmullRomPath(pts, scale) {
  const p = pts.map(([x, y]) => [100 + (x - 100) * (scale || 1), 100 + (y - 100) * (scale || 1)])
  const n = p.length
  let d = `M ${p[0][0].toFixed(1)},${p[0][1].toFixed(1)} `
  for (let i = 0; i < n; i++) {
    const p0 = p[(i - 1 + n) % n], p1 = p[i], p2 = p[(i + 1) % n], p3 = p[(i + 2) % n]
    const c1x = p1[0] + (p2[0] - p0[0]) / 6, c1y = p1[1] + (p2[1] - p0[1]) / 6
    const c2x = p2[0] - (p3[0] - p1[0]) / 6, c2y = p2[1] - (p3[1] - p1[1]) / 6
    d += `C ${c1x.toFixed(1)},${c1y.toFixed(1)} ${c2x.toFixed(1)},${c2y.toFixed(1)} ${p2[0].toFixed(1)},${p2[1].toFixed(1)} `
  }
  return d + "Z"
}

// ── the restrained palette ───────────────────────────────────────────────────
const INK = {
  lavender: "#B9A3D4",
  plum: "#8B6B9E",
  mauve: "#C9A0D8",
  blush: "#E3B8C9",
  lilac: "#DCD3EC",
}

// One star = two layered washes sharing the same silhouette: a larger, more
// blurred "bleed" behind, and a smaller, slightly denser "core" in front —
// the two-layer trick that reads as watercolor without any raster texture.
// Swap in real transparent PNG/SVG assets later by replacing just this
// component's return value; every call site below stays the same.
function WatercolorStar({ seed, spikes, size, color, opacity, rotate, style }) {
  const d = catmullRomPath(starPoints(seed, spikes || 5))
  const id = "pgStar" + seed
  return (
    <svg width={size} height={size} viewBox="0 0 200 200" style={{ position: "absolute", display: "block", transform: `rotate(${rotate || 0}deg)`, mixBlendMode: "multiply", ...style }}>
      <defs>
        <radialGradient id={id} cx="50%" cy="50%" r="65%">
          <stop offset="0%" stopColor={color} stopOpacity={opacity} />
          <stop offset="100%" stopColor={color} stopOpacity="0" />
        </radialGradient>
      </defs>
      <path d={d} fill={`url(#${id})`} style={{ filter: "blur(7px)" }} />
      <path d={catmullRomPath(starPoints(seed, spikes || 5), 0.8)} fill={color} opacity={opacity * 0.85} style={{ filter: "blur(3px)" }} />
    </svg>
  )
}

// A soft, cohesive base — cream easing into pale lilac and plum. Deliberately
// simple: one gradient, no scene, no busy layering underneath the stars.
const PROGRESS_BG = () => "linear-gradient(180deg,#FDFBFA 0%,#F8F2F7 32%,#F0E7F0 62%,#E7DCEC 100%)"

export function ProgressAir() {
  // Placement mirrors the requested layout: one large star bleeding in from
  // the upper-right border; one partially cropped along the left near
  // Capacity/Movement; a larger muted one lower down (percentage-based so it
  // lands "farther down" proportionally on both short and long pages, since
  // Progress's real height depends entirely on how much the person has
  // logged); and two very soft ones anchored to the true bottom of the page
  // near Wins, however tall that page turns out to be.
  return (
    <div style={{ position: "absolute", inset: 0, pointerEvents: "none", overflow: "hidden" }}>
      <WatercolorStar seed={5} spikes={5} size={340} color={INK.lavender} opacity={0.16} rotate={-8}
        style={{ top: -60, right: -90 }} />
      <WatercolorStar seed={12} spikes={6} size={260} color={INK.plum} opacity={0.13} rotate={14}
        style={{ top: 460, left: -110 }} />
      <WatercolorStar seed={23} spikes={5} size={300} color={INK.mauve} opacity={0.12} rotate={5}
        style={{ top: "46%", right: -120 }} />
      <WatercolorStar seed={31} spikes={5} size={200} color={INK.blush} opacity={0.14} rotate={-18}
        style={{ bottom: 260, left: -70 }} />
      <WatercolorStar seed={40} spikes={6} size={230} color={INK.lilac} opacity={0.18} rotate={9}
        style={{ bottom: -80, right: -60 }} />
    </div>
  )
}

export { PROGRESS_BG }
